version: '3.9'

services:
  app:
    container_name: app
    build: .
    volumes:
      - ./front:/app
    ports:
      - 80:3000
    restart: always
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npx nodemon"

